### ISSUE TITLE
Fix at docker-compose-use-modules-from-git-clones.yml

### ISSUE THREAD

**Issue by assuom7827** [IMIO/docker-teleservices#1]
docker-teleservices/teleservices/Dockerfile-use-modules-from-git-clones

there are many error at the compose process 

deb http://http.debian.net/debian jessie-backports main
RUN apt install python-pip python-pytest-django

**Comment by frederic-peters** [comment]
That branch has been merged in master, and is obsolete.

**Comment by assuom7827** [comment]
in the readme file the docker-composer uses the jessie image. how to change for pred version version

**Comment by frederic-peters** [comment]
This is not a support forum.

Use docker-compose-stretch.yml to get an image built against stretch.
